In [1]:
#standardiz the data#
#convert into guassian distribution
from numpy import set_printoptions
from sklearn.preprocessing import StandardScaler
from pandas import read_csv
import pandas as pd
import numpy as np
filename="indians-diabetes.data.csv"

hnames=['preg','plas','pres','skin','test','mass','pedi','age','class']

dataframe= pd.read_csv(filename,names=hnames)

array=dataframe.values

X=array[:,0:8]
Y=array[:,8]

scalar=StandardScaler()
rescaledX=scalar.fit_transform(X)

print(rescaledX[:30,:])


print("\n\nMean of First coloum")
print(np.mean(rescaledX[:,0]))

[[ 0.63994726  0.84832379  0.14964075  0.90726993 -0.69289057  0.20401277
   0.46849198  1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575  0.53090156 -0.69289057 -0.68442195
  -0.36506078 -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 -1.28821221 -0.69289057 -1.10325546
   0.60439732 -0.10558415]
 [-0.84488505 -0.99820778 -0.16054575  0.15453319  0.12330164 -0.49404308
  -0.92076261 -1.04154944]
 [-1.14185152  0.5040552  -1.50468724  0.90726993  0.76583594  1.4097456
   5.4849091  -0.0204964 ]
 [ 0.3429808  -0.15318486  0.25303625 -1.28821221 -0.69289057 -0.81134119
  -0.81807858 -0.27575966]
 [-0.25095213 -1.34247638 -0.98770975  0.71908574  0.07120427 -0.12597727
  -0.676133   -0.61611067]
 [ 1.82781311 -0.184482   -3.57259724 -1.28821221 -0.69289057  0.41977549
  -1.02042653 -0.36084741]
 [-0.54791859  2.38188392  0.04624525  1.53455054  4.02192191 -0.18943689
  -0.94794368  1.68125866]
 [ 1.23388019  0.12848945  1.39038675 -1.28821221 -0.69289057 -4.06047387
  -0.7244549   1.7

In [2]:
#binarised
from sklearn.preprocessing import Binarizer
from pandas import read_csv
import numpy as np
import pandas as pd

filename="indians-diabetes.data.csv"
hnames=['preg','plas','pres','skin','test','mass','pedi','age','class']

dataframe= pd.read_csv(filename,names=hnames)

array=dataframe.values
#separate into input and output components
X=array[:,0:8]
Y=array[:,8]

binarizer=Binarizer(threshold=6)

binaryX=binarizer.fit_transform(X)
#summarize transform data
print(binaryX[0:30,:])

[[0. 1. 1. 1. 0. 1. 0. 1.]
 [0. 1. 1. 1. 0. 1. 0. 1.]
 [1. 1. 1. 0. 0. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [0. 1. 1. 0. 0. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 0. 0. 0. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 0. 0. 0. 1.]
 [0. 1. 1. 0. 0. 1. 0. 1.]
 [1. 1. 1. 0. 0. 1. 0. 1.]
 [1. 1. 1. 0. 0. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 0. 0. 0. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 0. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 0. 1. 0. 1.]
 [1. 1. 1. 0. 0. 1. 0. 1.]
 [1. 1. 1. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 0. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1.]
 [0. 1. 1. 0. 0. 1. 0. 1.]]


In [3]:
#normalize the data
from sklearn.preprocessing import Normalizer
from pandas import read_csv
from numpy import set_printoptions
import pandas as pd
import numpy as np
filename="indians-diabetes.data.csv"

hnames=['preg','plas','pres','skin','test','mass','pedi','age','class']

dataframe= pd.read_csv(filename,names=hnames)

array=dataframe.values

X=array[:,0:8]
Y=array[:,8]

scalar=Normalizer()
rescaledX=scalar.fit_transform(X)

print(rescaledX[:30,:])
set_printoptions(precision=2)
# print(normalisedX[0:30,:])

[[3.35523701e-02 8.27625129e-01 4.02628441e-01 1.95722159e-01
  0.00000000e+00 1.87893272e-01 3.50622267e-03 2.79603084e-01]
 [8.42400400e-03 7.16040340e-01 5.55984264e-01 2.44296116e-01
  0.00000000e+00 2.24078506e-01 2.95682540e-03 2.61144124e-01]
 [4.03976822e-02 9.24096981e-01 3.23181458e-01 0.00000000e+00
  0.00000000e+00 1.17658249e-01 3.39340531e-03 1.61590729e-01]
 [6.61199291e-03 5.88467369e-01 4.36391532e-01 1.52075837e-01
  6.21527334e-01 1.85797001e-01 1.10420282e-03 1.38851851e-01]
 [0.00000000e+00 5.96386300e-01 1.74127387e-01 1.52361463e-01
  7.31335024e-01 1.87622259e-01 9.96008652e-03 1.43655094e-01]
 [3.49109576e-02 8.09934216e-01 5.16682173e-01 0.00000000e+00
  0.00000000e+00 1.78744103e-01 1.40342050e-03 2.09465746e-01]
 [2.17653979e-02 5.65900344e-01 3.62756631e-01 2.32164244e-01
  6.38451670e-01 2.24909111e-01 1.79927289e-03 1.88633448e-01]
 [8.05506369e-02 9.26332325e-01 0.00000000e+00 0.00000000e+00
  0.00000000e+00 2.84343748e-01 1.07937853e-03 2.33596847e-01]


In [4]:
import pandas as pd
import warnings
warnings.filterwarnings(action="ignore")
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
filename="indians-diabetes.data.csv"
hnames=['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe= pd.read_csv(filename,names=hnames)
array=dataframe.values
#separate into input and output components
X=array[:,0:8]
Y=array[:,8]
test_data_size=0.33
seed=7
X_train,X_test,Y_train,Y_test= train_test_split(X,Y,test_size=test_data_size,random_state=seed)

model=LogisticRegression()
model.fit(X_train,Y_train)
result=model.score(X_test,Y_test)
print("Accuracy =%f%%"%(result*100))


Accuracy =78.740157%


In [5]:
import pandas as pd
import warnings
warnings.filterwarnings(action='ignore')
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
filename="indians-diabetes.data.csv"
hnames=['preg','plas','pres','skin','test',"mass",'b','class','s']
dataframe=pd.read_csv(filename,names=hnames)
array= dataframe.values
X=array[:, 0:8]
Y=array[:,8]
model=LogisticRegression()

num_folds=10
kfold=KFold(n_splits=num_folds)
results=cross_val_score(model,X,Y,cv=kfold)

print("result:",results)
print("accuracy:%.3f%%"%(results.mean()*100.0))
print("Std.Deviation=%.3f"%(results.std()*100))

result: [0.7  0.81 0.75 0.69 0.77 0.74 0.84 0.82 0.74 0.8 ]
accuracy:76.564%
Std.Deviation=4.859


In [6]:
#logistic LogisticRegression
#LeaveOneOut  technique
import pandas as pd
import warnings
warnings.filterwarnings(action="ignore")
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
filename="indians-diabetes.data.csv"
names=['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe= pd.read_csv(filename,names=names)
array=dataframe.values
#separate into input and output components
X=array[:,0:8]
Y=array[:,8]
loocv=LeaveOneOut()
model=LogisticRegression()
results=cross_val_score(model,X,Y,cv=loocv)

print("results:",results)
print("results.size:",results.size)

print("sum of positive results:%i"%(results.sum()))

print("accuracy=%2.f%%"%(results.sum()*100/results.size))


results: [1. 1. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0.
 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 1.
 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 0. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1.
 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 1. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.
 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1.
 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1.
 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 1.
 0. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 0. 1. 1. 0.
 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 0. 1. 1. 0. 1. 0. 0.
 1. 1. 1. 0. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1.
 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1.

In [ ]:
#
import warnings
warnings.filterwarnings(action="ignore")
import numpy as np
import pandas as pd
from sklearn.model_selection import ShuffleSplit

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
filename='indians-diabetes.data.csv'
names=['preg','plas',"a",'s','d','e','p','es',"sd"]
dataframe=pd.read_csv(filename,names=names)
array=dataframe.values
X=array[:,0:8]
Y=array[:,8]
test_data_size=0.33
no_of_repetitions=4
shufflesplit=ShuffleSplit(n_splits=no_of_repetitions,test_size=test_data_size)

model=LogisticRegression()
results=cross_val_score(model,X,Y,cv=ShuffleSplit)

print("results:",results)
print("results.size:",results.size)

print("sum of positive results:%i"%(results.sum()))

print("accuracy=%2.f%%"%(results.sum()*100/results.size))

In [ ]:
import pandas as pd
import warnings
warnings.filterwarnings(action='ignore')
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
filename="indians-diabetes.data.csv"
hnames=['preg','plas','pres','skin','test',"mass",'b','class','s']
dataframe=pd.read_csv(filename,names=hnames)
array= dataframe.values
X=array[:, 0:8]
Y=array[:,8]
model=LogisticRegression()

kfolds=10
kfold=KFold(n_splits=kfolds)
results=cross_val_score(model,X,Y,cv=kfold)

scoringMethod="accuracy"
results=cross_val_score(model,X,Y,cv=kfold,scoring=scoringMethod)

print("accuracy :%.3f(%.3f)"%(results.mean()*100,results.std()*100))



In [ ]:
import pandas as pd
import warnings
warnings.filterwarnings(action='ignore')
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
filename="indians-diabetes.data.csv"
hnames=['preg','plas','pres','skin','test',"mass",'b','class','s']
dataframe=pd.read_csv(filename,names=hnames)
array= dataframe.values
X=array[:, 0:8]
Y=array[:,8]
model=LogisticRegression()

kfolds=10
kfold=KFold(n_splits=kfolds)
results=cross_val_score(model,X,Y,cv=kfold)

scoringMethod='neg_log_loss'    #"accuracy"
results=cross_val_score(model,X,Y,cv=kfold,scoring=scoringMethod)

print("accuracy :%.3f(%.3f)"%(results.mean(),results.std()))



In [ ]:
import pandas as pd
import warnings
warnings.filterwarnings(action='ignore')
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
filename="indians-diabetes.data.csv"
hnames=['preg','plas','pres','skin','test',"mass",'b','class','s']
dataframe=pd.read_csv(filename,names=hnames)
array= dataframe.values
X=array[:, 0:8]
Y=array[:,8]
test_size=0.33
seed=7
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size,random_state=seed)

model=LogisticRegression()
model.fit(X_train,Y_train)

predicted=model.predict(X_test)
matrix=confusion_matrix(Y_test,predicted)

print(matrix)

In [ ]:
import pandas as pd
import warnings
warnings.filterwarnings(action='ignore')
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
filename="indians-diabetes.data.csv"
hnames=['preg','plas','pres','skin','test',"mass",'b','class','s']
dataframe=pd.read_csv(filename,names=hnames)
array= dataframe.values
X=array[:, 0:8]
Y=array[:,8]
test_size=0.33
seed=7
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=test_size, random_state=seed)

model=LogisticRegression()
model.fit(X_train,Y_train)

predicted=model.predict(X_test)
matrix=classification_report(Y_test,predicted)

print(matrix)

In [ ]:
from pandas import  read_csv
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression

filename='housing.csv'
hnames=['a','s','d','f','g','h','j','k','l','10','11','12','13','14']
dataframe=read_csv(filename,names=hnames)
array=dataframe.values
x=array[:,0:13]
y=array[:,13]

kfold=KFold(n_splits=10)
model=LinearRegression()

scoringMethod='neg_mean_absolute_error'
results=cross_val_score(model,x,y,cv=kfold,scoring=scoringMethod)

print(results)
print("MAE: %.3f(%.3f)"%(results.mean(),results.std()))


In [ ]:
from pandas import  read_csv
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression

filename='housing.csv'
hnames=['a','s','d','f','g','h','j','k','l','10','11','12','13','14']
dataframe=read_csv(filename,names=hnames)
array=dataframe.values
x=array[:,0:13]
y=array[:,13]

kfold=KFold(n_splits=10)
model=LinearRegression()
scoringMethod='r2'
results=cross_val_score(model,x,y,cv=kfold,scoring=scoringMethod)

print(results)
print("r^2: %.3f"%results.mean())


In [ ]:
import warnings
warnings.filterwarnings(action="ignore")
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
filename=('indians-diabetes.data.csv')
headingnames=['1','2','3','4','5','6','7','8','9']
dataframe=pd.read_csv(filename,names=headingnames)
array=dataframe.values
x=array[:,0:8]
y=array[:,8]

kfold=KFold(n_splits=10)

#spot checkings for logistic regression
#===================================================================================================
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
results=cross_val_score(model,x,y,cv=kfold)
print("validation score of LogisticRegression:",results.mean())

#2===================================================================================================
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
model=LinearDiscriminantAnalysis()
results=cross_val_score(model,x,y,cv=kfold)
print("validation score of Linear discriminant analysis",results.mean())
#  3  ====================================================================================
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier()
results=cross_val_score(model,x,y,cv=kfold)
print("validation score for kNN",results.mean())



##  4  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
results=cross_val_score(model,x,y,cv=kfold)
print("validation score for GaussianNB:",results.mean())

#5spot checking for classification

from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
results=cross_val_score(model,x,y,cv=kfold)
print("validation for CART decision tree:",results.mean())

#6)sopt cheking for support vector machines(svm)
#---------------------------------------------------------------------------

from sklearn.svm import SVC
model=SVC()
results=cross_val_score(model,x,y,cv=kfold)
print("validation score for SVM:", results.mean())


